### PR TITLE
Swift

### PR DESCRIPTION
**Pull request by fitomad**
Added **Swift** programming language badge.

### CODE REVIEW

**Comment by ekfuhrmann** [comment]
Hi @fitomad, I'm bringing this project back from the dead!

If you don't mind, could you possibly remove your SVG submission from the commit due to it not having the proper font outlining?  I'll be creating a badge based on your design with the correct styles so there is no need for that file.

Thanks.

**Comment by fitomad** [comment]
:+1:

**Comment by christoga** [comment]
This branch has conflict bruh..

**Comment by ekfuhrmann** [comment]
[I resolved this issue and pushed latest to the repo.](https://github.com/BraveUX/for-the-badge/commit/77a1bee622b5e9a131f2aab4e699770291b2b311)

As such I'm going to close this request.

**Pull request closed without merging**
