### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by diomed**
added a couple of things

### CODE REVIEW

**Comment by ekfuhrmann** [comment]
This is intended to be satirical, memeish, and fun hence the goofy nature of many of these tags. While there is room for some more straight-edge badges, removing ones such as `Validated HTML2` is missing the purpose behind the badges.

As such, please feel free for more badge contributions but keep them lighthearted and fun, and do not remove any from that list. We want to avoid breaking people's links who may be currently using them.

**Comment by diomed** [comment]
couldnt u just delete that line then merge it, instead of closing it all?
and what about other open PR's??

**Comment by ekfuhrmann** [comment]
I've just gone through and updated any outstanding PR's. A new build will be coming out shortly with a bunch of updates and fixes.

**Comment by diomed** [comment]
@ekfuhrmann 

how are these images even created? I thought app generates them automatically.
was I wrong? coz I see no new ones.

**Comment by ekfuhrmann** [comment]
They are designed individually in illustrator, hence the slow turnaround on accepting PR's. We tend to only add them in waves rather than as requests come in.

I've pushed a new build to our FTP, so you should be seeing changes shortly. I'll be updating the repo with the current build thereafter.

**Comment by ekfuhrmann** [comment]
@diomed Update is all done and now live. See the README.md for more info. If you don't see the new changes yet, please try clearing your cache or giving it some time to purge the old images.

If you have any questions please don't hesitate to ask!

**Pull request closed without merging**
