### PR TITLE
Add "Should Designers Code"

### PR DESCRIPTION
**Pull request by mattrothenberg**
Howdy!

Would it be possible to add the following "Should Designers Code?" badge to the list? I'd love to use it on my most recent OSS project. Happy to make any tweaks/adjustments.

✌️

### CODE REVIEW

**Comment by ekfuhrmann** [comment]
Not a huge fan of having a question for a badge; it doesn't make much sense to me.

**Comment by mattrothenberg** [comment]
Fair enough, I'll close this up.

**Comment by ekfuhrmann** [comment]
Thanks, if you have any other suggestions please don't hesitate to put them out there.

I wasn't sure the direction you wanted to go with the badge you suggested, but something like `Design It | Code It` could work.

**Comment by mattrothenberg** [comment]
"Should Designers Code?" is a meme in the Product Design community. "Design It | Code It" doesn't have the same _punch_, if you will.

Thanks anyways!

**Comment by ekfuhrmann** [comment]
Hah, I figured it was something along those lines. Appologies

**Pull request closed without merging**
