### PR TITLE
Added Whiskey + H9RBS.js

### PR DESCRIPTION
**Pull request by Neema**
Added a new section "dependencies" with one value for now... Whiskey 
and added H9RBJS.js (html9responsiveboilerstrapjs.com)  to the "uses" section

### CODE REVIEW

**Comment by Neema** [comment]
On second thought though - maybe H9RB.JS makes more sense in the "built with" section?

**Comment by ekfuhrmann** [comment]
Hi @Neema, this project is intended to be a joke (see our about section) rather than for practical use. While I appreciate your suggestions and see their value, they don't make much sense for what we have going on here.

As such I encourage you to please submit some badge ideas of your own, but make sure they fall in-line with what this site really is -- _a joke_.

Thanks!

**Comment by Neema** [comment]
Not sure if you've seen it before but H9RB.js is a joke itself too. 

http://html9responsiveboilerstrapjs.com/

**Comment by ekfuhrmann** [comment]
Whoosh, solid. Will add in next build coming out later today.

**Pull request closed without merging**
