### PR TITLE
Added 5 badges

### PR DESCRIPTION
**Pull request by andersonaddo**
Powered by Black Magic 
Powered by Energy Drinks
Powered by Overtime
0% Optimized
Contains Tasty Spaghetti Code

### CODE REVIEW

**Comment by ngehlert** [comment]
you only added them to the readme. svgs are missing

**Comment by andersonaddo** [comment]
Oh my bad! I thought I read somewhere that svgs would only bee needed if the badges wanted special icons or features! 
I’ll add them then.

**Comment by andersonaddo** [comment]
I added the svgs, though from the looks of things it doesn't look like this repo will be updated anytime soon :/

**Comment by ngehlert** [comment]
@andersonaddo yeah unfortunately that is probably true :( just thought maybe if it will get updated then at least most of the PRs should be ready to be accepted ;) also this way someone can at least copy-paste your svg :D

**Comment by by-k4y4k** [comment]
@andersonaddo I know that this is a bit of a necropost but I just had to stop by and tell you that I've been uncontrollably laughing at `0% Optimised` for the past 15 minutes

**Comment by MostHated** [comment]
You can optimize when you are dead. Until then, just keep on developing.

**Comment by ekfuhrmann** [comment]
Sorry for the delay in getting to these PR's but this is finally being accepted. I made a few minor changes to file names so that they play nice with this spaghetti code of a project, but otherwise everything checks out.

Thank you so much for your patience and for the PR!

**Pull request merged**
