### PR TITLE
Added "made with typescript" badge

### PR DESCRIPTION
**Pull request by scout119**
Made this badge using Inkscape. I have more once this first one will get through.

### CODE REVIEW

**Comment by rahulkp220** [comment]
Hi @scout119, can you also make one for Julia? https://github.com/BraveUX/for-the-badge/issues/68

**Comment by scout119** [comment]
@rahulkp220  Sure, as soon as this PR got accepted. I want to make sure there are no issues first.

**Comment by rahulkp220** [comment]
@scout119 Awesome! thanks 🥇

**Comment by scout119** [comment]
@rahulkp220 
Elixir
Julia

**Comment by scout119** [comment]
@rahulkp220 Check it out.
[Made with Elixir](https://github.com/scout119/for-the-badge/blob/set1/src/images/badges/made-with-elixir.svg)
[Made with Julia](https://github.com/scout119/for-the-badge/blob/set1/src/images/badges/made-with-julia.svg)

**Comment by rahulkp220** [comment]
Cool! Let's see if they get merged quickly.

**Comment by pBouillon** [comment]
Will this ever be merged ?

**Comment by xv** [comment]
Please merge.

cry

**Comment by jdreben** [comment]
+1 to getting this and the Julia badge merged! Please. Enable us to go forth and bravely honor these great
 languages.

**Comment by ekfuhrmann** [comment]
Thanks for taking the time to make this @scout119 and apologies for taking so long to merge.

**Comment by scout119** [comment]
Awesome! 

Thank you @ekfuhrmann  for merging the PR! I have just created a new one #112 for the badges that were discussed here and a few more.

Thanks again!

**Pull request merged**
