### PR TITLE
Contains Technical Debt

### PR DESCRIPTION
**Pull request by duncm**
For those projects stuck in a corporate hellhole of project-managed bullshit.

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Please. Yes.

**Comment by lynnaloo** [comment]
+1

**Comment by Heliosmaster** [comment]
:+1:

**Comment by MichalZalecki** [comment]
:+1:

**Comment by benhylau** [comment]
[forthebadge](http://forthebadge.com)

**Pull request merged**
