### PR TITLE
Added Creative commons badges

### PR DESCRIPTION
**Pull request by kerunaru**
I propose black and white as colors for these badges :+1:

### CODE REVIEW

**Comment by jaxgeller** [comment]
Can you explain the acronyms?

**Comment by kerunaru** [comment]
Sure!

+ CC-BY: Creative Commons - Attribution
+ CC-NC: Creative Commons - No commercial use
+ CC-NC-SA: Creative Commons - No commercial use and share alike
+ CC-BY-ND: Creative Commons - Attribution and no derivative work
+ CC-SA: Creative Commons - Share alike
+ CC-BY-ND: Creative Commons - Attribution and no derivative work
+ CC0: Creative Commons - Zero license (Public domain)

**Comment by RaoOfPhysics** [comment]
:+1:

**Comment by kerunaru** [comment]
Reason?

**Comment by ekfuhrmann** [comment]
Working on the badges, will update when done

**Comment by ekfuhrmann** [comment]
@kerunaru CC Badges have now been added and the Readme has been updated to reflect as much.

**Comment by kerunaru** [comment]
@ekfuhrmann sweet!

**Pull request closed without merging**
